# Generated by Django 6.0.5 on 2026-06-14 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='herocontent',
            options={'ordering': ['-created_at']},
        ),
    ]
