services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    volumes:
      - sqlite_data:/app/db.sqlite3
      - media_data:/app/media
      - static_data:/app/staticfiles

volumes:
  sqlite_data:
  media_data:
  static_data:
