# Generated by Django 6.0.5 on 2026-06-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='metric',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
