# Generated by Django 6.0.5 on 2026-06-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='company',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='contact',
            name='service',
            field=models.CharField(blank=True, choices=[('meta-tiktok-ads', 'Meta & TikTok Ads'), ('shopify', 'Shopify Development'), ('wordpress', 'WordPress Development'), ('social-media', 'Social Media Management'), ('seo', 'SEO & Digital Marketing'), ('branding', 'Branding & Design'), ('other', 'Other')], default='', max_length=30),
        ),
    ]
